### ISSUE TITLE
Change JS alerts into modals

### ISSUE THREAD

**Issue by 4D44H** [ILSCeV/lara-vedst#100]
Users need to be informed about errors or successes after actions were taken.
We now do this partially with JS-alerts and partially with a message shown in a small div popping up at the top of the screen.

* [x] For all JavaScript alerts / confirm dialogs -> show a modal instead: https://getbootstrap.com/javascript/#modals
* [x] add correct CSS styles: https://bootswatch.com/paper/#dialogs

**Comment by 4D44H** [comment]
FYI issue number 100!  :tada: :beer: :dancers:

**Comment by 4D44H** [comment]
Thanks @stefanheyder!

**Comment by 4D44H** [comment]
Please also implement with overriding JS alerts.

**Comment by stefanheyder** [comment]
Which events triggered the alerts? I am currently looking into it.

**Comment by 4D44H** [comment]
As an example, event/survey deletion and survey answer deletion. But I'd rather just look for all "alert(" fields in the lara-vedst folder.

**Comment by stefanheyder** [comment]
Solved by c283f20f787a6bbf93b1fe2f54a9253fd572334c .
