### ISSUE TITLE
Automatically check both clubs if event you create is internal

### ISSUE THREAD

**Issue by 4D44H** [ILSCeV/lara-vedst#126]
While creating a new event, if a user chooses an internal type, then let the page automatically check all checkboxes in the "show to which clubs" area.
Handle this in browser via JavaScript.

ToDo:
* [x] create an function that waits for a change in radiobutton selection of event type
* [x] if event type is internal (1 -> info only / 4 -> internal event / 5 -> private party -> "Nutzung" / 6 -> cleaning -> "Fluten" / 9 -> internal task -> everything else) check all checkboxes (show to club 1, 2, ..., N)
* [x] make sure it's scalable - needn't rewrite the function if another section is added to the list of clubs
* [x] make sure it works both in Create View and Edit View

**Comment by 4D44H** [comment]
@stefanheyder it would be nice to have the script to not overwrite manual changes from user.
E.g. if the user fills filtering first (say, setting "cafe only") and chooses the event type later, the script shouldn't change event type back to "both".
But that only If you could find a clever way to do it, would be also ok without it :)

**Comment by stefanheyder** [comment]
@4D44H So the values that this should be triggered on are 4 and 5? I will create an array internalEvenValues, where you can then set the events that should trigger this behaviour.

**Comment by 4D44H** [comment]
@stefanheyder An array will be fine. I'd say all internal types:
1 -> info only 
4 -> internal event 
5 -> private party -> "Nutzung"
6 -> cleaning -> "Fluten" 
9 -> internal task -> "Sonstiges"

**Comment by 4D44H** [comment]
@stefanheyder: I thought about another thing here - if a user chooses "normal" again, should we switch back to single club filter?

**Comment by stefanheyder** [comment]
@4D44H so save the selected clubs and restore them if the user chooses an event not in the internalEventValues array? Sounds good to me.

**Comment by 4D44H** [comment]
@stefanheyder you can also do it easier - just set equal to what's in section field ("Sektion" - place)

**Comment by stefanheyder** [comment]
It would be easier if the checkboxes had a name / attribute that corresponded to the repspective club/ location. I.e. rename "filterShowToClub2" and "filterShowToClub3" to bc-club and bc-café. But I don't know where these names are used right now and changing those names would probably break something

**Comment by 4D44H** [comment]
@stefanheyder Club2 = club with id 2 in the DB
