### ISSUE TITLE
Add Google Calendar Integration

### ISSUE THREAD

**Issue by stefanheyder** [ILSCeV/lara-vedst#127]
Add an option for users to add their shifts to their google calendar. For this, the Google Calendar API (https://developers.google.com/google-apps/calendar/) can be used. 

Maybe add an option (set by the user) to do this automatically in the background after accepting a new shift. 

Also look at other calendar APIs.

**Comment by ThomDietrich** [comment]
Great idea!
Alternatively / Additionally, how about providing a more general iCal file / feed? This way a user will have his shifts or all events automatically pop up in his calendar:
https://github.com/markuspoerschke/iCal

**Comment by ThomDietrich** [comment]
Some more thoughts on that: With iCal you have way more possibilities but it's also harder to setup. On Android you'll need an extra app for example. Google Calendar integration on the other hand is limited to copying over one event to google calendar, but every user can directly use it without any setup on his device (if he/she uses google calendar).
Therefore I think both would be great, also together.

I could look into that, I have some background with ical and already thought about adding a ticket.

**Comment by 4D44H** [comment]
Why not both, iCal _and_ Google Calendar? Let the user decide.

**Comment by 4D44H** [comment]
https://stackoverflow.com/questions/10488831/link-to-add-to-google-calendar

**Comment by ThomDietrich** [comment]
Hey guys, I'm sorry but I will not be able to work on this in the near future. Too many other tasks... :-/

**Comment by 4D44H** [comment]
@ThomDietrich no problem! But I hope you'll stick around to give us some feedback from time to time? It's always welcome :)

**Comment by 4D44H** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[2] Month: Add Google Calendar Integration](https://trello.com/c/jkxFepOR/59-2-month-add-google-calendar-integration)

**Comment by 4D44H** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[1] Events: Add Google Calendar Integration](https://trello.com/c/IJkrHeJ8/60-1-events-add-google-calendar-integration)

**Comment by 4D44H** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[1] Surveys: Add Google Calendar Integration](https://trello.com/c/uyqMnEud/61-1-surveys-add-google-calendar-integration)

**Comment by 4D44H** [comment]
Google Calendar event creation implemented - closing this ticket.
For the feed see next ticket referenced below.

**Comment by ThomDietrich** [comment]
Great work guys! ;)
