### ISSUE TITLE
Change the color of the shift if someone enters / deletes a name

### ISSUE THREAD

**Issue by stefanheyder** [ILSCeV/lara-vedst#158]
![updateshiftcolor](https://cloud.githubusercontent.com/assets/16904680/17456340/d71a9538-5bd4-11e6-87c1-3e8b6266b29e.gif)
![updateshiftcolorinsert](https://cloud.githubusercontent.com/assets/16904680/17456341/d71edb16-5bd4-11e6-9d14-f3a612b8aec3.gif)

If the status of a shift changes, we should change the color of the shift name accordingly.

**Comment by stefanheyder** [comment]
![updateshiftcolorfix](https://cloud.githubusercontent.com/assets/16904680/17456561/0f80067c-5bdc-11e6-8e84-490cbfbccbeb.gif)
This is how it looks right now on my branch. I check the ajax response for userStatus.tile = "Dienst frei" and change the class of the div accordingly. Is there a more elegant way to check if there is someone doing the shift?

**Comment by 4D44H** [comment]
It would be better to check the username instead, because the status title might be changed / formulated differently. 
If userName.value = "" (empty) then mark that schedule entry as free.
