### ISSUE TITLE
Survey Revisions show entries from earlier dates and other events

### ISSUE THREAD

**Issue by 4D44H** [ILSCeV/lara-vedst#175]
A survey was just created, yet already has history values.
![image](https://cloud.githubusercontent.com/assets/11014468/18028088/287a31da-6c75-11e6-9768-3d858852f1de.png)

**Comment by 4D44H** [comment]
@LudwigBr any idea where this might come from?

**Comment by LudwigBr** [comment]
My first guess would be manual database interaction. Do you maybe deleted a survey directly in the database and therefore the new survey got the same id?
On the other hand I would expect more and other previous entries in this case.
I will check back later today and do some further investigation.

**Comment by 4D44H** [comment]
I used an old db export, but did not delete anything manually.
Thank you!

**Comment by 4D44H** [comment]
Fixed by Ludwig, thanks!
