### ISSUE TITLE
Bug: surveys can't be edited

### ISSUE THREAD

**Issue by 4D44H** [ILSCeV/lara-vedst#182]
To reproduce:
- checkout branch release-2.1.2
- create a new survey with at least 1 question
- press "edit" button
- don't change anything
- press "save"
- Result:
  ![image](https://cloud.githubusercontent.com/assets/11014468/18225453/34ceee6c-71f2-11e6-8f74-3c0f9d83c2e2.png)

Also:
- can't add/remove questions because of this
- console says "edit:336 Uncaught ReferenceError: check_question_type is not defined" for /views/partials/surveyForm.blade.php @ line 241

@MPostler or @achim91 - any ideas how to fix this? I think this was your code.

**Comment by stefanheyder** [comment]
There is a reference error : 
`
edit:336 Uncaught ReferenceError: check_question_type is not defined
`
Probably comes from calling the function before the corresponding script is loaded.

**Comment by stefanheyder** [comment]
@MPostler @achim91 can you take a look at #184 an check that this does not  break anything?

**Comment by 4D44H** [comment]
We will use the current fix from Stefan for current release, but if you'll find a more elegant solution we'll be happy to see it.

**Comment by 4D44H** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[2] Surveys: surveys can't be edited](https://trello.com/c/itcADBTk/32-2-surveys-surveys-can-t-be-edited)

**Comment by 4D44H** [comment]
Fixed.
