### ISSUE TITLE
Bug: guests answering a survey are logged in revisions as "Susi"

### ISSUE THREAD

**Issue by 4D44H** [ILSCeV/lara-vedst#183]
To reproduce:
- create or open a survey
- log out if you are logged in
- add an answer (as a guest)
- log back in, look at revisions:
![image](https://cloud.githubusercontent.com/assets/11014468/18225576/16b75ce4-71f6-11e6-9b7f-c03143230e96.png)
- In the DB: revisions.creator_id = NULL

@LudwigBr ?

**Comment by 4D44H** [comment]
"Susi" is saved in DB in the table "persons" with :
- id "5"
- prsn_name "Susi"
- prsn_ldap_id "NULL"
- prsn_status "" (empty string)
- clb_id "4"
Maybe the first Person with ldap_id = NULL is taken?

**Comment by LudwigBr** [comment]
> Maybe the first Person with ldap_id = NULL is taken?

That's it. It can be corrected in SurveyController line 263+. If its not urgent I will fix it after this weekend.

**Comment by 4D44H** [comment]
Thanks, I'd appreciate a fix from you, as I am not very familiar with your code yet - it would probably take longer to do it myself :)

It's not urgent, the issue is minor - worst case I'll just inject a user named "guest" into the beginning of the DB. And also I can't push to production before #182 is fixed anyway, so we have some time. Btw, if you have any idea about that one please comment.

**Comment by 4D44H** [comment]
@LudwigBr we will use the quick fix from Stefan for current release, but if you'll find a more elegant solution I'll be happy to see it.

**Comment by LudwigBr** [comment]
the "quick fix" seems to be what I would have done, I think its as elegant as possible.

**Comment by 4D44H** [comment]
Perfect, thank you both! I'll close this issue then.
