### ISSUE TITLE
Rewrite month view for mobile - list of events instead of a table

### ISSUE THREAD

**Issue by 4D44H** [ILSCeV/lara-vedst#68]

**Comment by ThomDietrich** [comment]
"list of events" would be what is called agenda. in my opinion that's something different.
How about a minimized calendar without text - just colored boxes that after a click will show all details in a bootstrap popover.

**Comment by 4D44H** [comment]
This is currently being worked on here: [Softwareproject at TU Ilmenau](https://github.com/tuiSSE/lara-vedst/issues/)

**Comment by 4D44H** [comment]
Implemented in 2.1.0-beta.5
